server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 86400000 # 过期时间 24h
      cache-null-values: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 604800000 # 7 days
    refresh-expiration: 2592000000 # 30 days

auth:
  white-list:
    - /user/login/mobile
    - /user/code/**
    - /images/** # 静态资源
